[theme]

# Primary accent for interactive elements
primaryColor = '#806254'

# Background color for the main content area
backgroundColor = '#a69b2d'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#806254'

# Color used for almost all text
textColor = 'white'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"